---
- hosts: qlean
  tasks:
    - name: Check infrastructure git version
      shell: git pull
      register: git_status
      delegate_to: 127.0.0.1

    - pause:
        seconds: 10

    - name: debug
      debug:
        msg: "{{ git_status.stdout }}"

    - include: updated.yml